### ISSUE TITLE
why in days week have difference in new year?

### ISSUE THREAD

**Issue by MortezaFathnia** [A-Kasaaian/react-advance-jalaali-datepicker#23] opened 2019-06-23 05:22 UTC
this datepicker in week's day is set of last year, example 1398/04/02 is Saturday.

**Comment by A-Kasaaian** [comment] 2019-06-23 10:41
Please, follow issue report template, explain the exact issue and if applicable, leave the piece of code.

**Comment by MortezaFathnia** [comment] 2019-06-23 10:47
![2019-06-23](https://user-images.githubusercontent.com/16924889/59975138-ef768d80-95c9-11e9-8771-4cbb1a5e41d4.png)
day not match with date

**Comment by A-Kasaaian** [comment] 2019-06-23 20:06
I can't replicate it. Everything seems fine with the latest release.

**Comment by A-Kasaaian** [comment] 2019-06-23 20:24
It seems strange !!!

**Comment by MortezaFathnia** [comment] 2019-06-23 20:29
Maybe I have mistake, I'll try share my code.

**Comment by MortezaFathnia** [comment] 2019-06-24 05:45
Are you sure module is working correct?
please share your code or link
```
import React, { Component } from 'react';
import { DatePicker } from 'react-advance-jalaali-datepicker';
class UserRegister extends Component {
render() {
    return (
                 <DatePicker
                      placeholder="تاریخ تولد"
                      format="jYYYY/jMM/jDD"
                      onChange={this.change.bind(this)}
                      id="datePicker"
                      preSelected={
                        '1398/04/03'
                      }
                      cancelOnBackgroundClick="App"
                    />
                    )
       }
      }
   
export default UserRegister;
```

**Comment by A-Kasaaian** [comment] 2019-06-24 12:37
It's strange. The only issue is the `cancelOnBackgroundClick` its value should be boolean, but that still work. There is nothing wrong with the code. Please update to 1.2.2 and see if it occurs again.

There is no other report of such an issue. If it's possible leave the url of this page here.

Issue report format contains: OS, browser name, version and other env parameters like library version. As I mentioned in first comment, please follow [issue report](https://github.com/A-Kasaaian/react-advance-jalaali-datepicker/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) format. It helps a lot.

**Comment by A-Kasaaian** [comment] 2019-07-10 14:54
@MortezaFathnia I close this issue as you have not replied for over 2 weeks. In case the issue is remained, reopen it.

**Closed by A-Kasaaian** 2019-07-10 14:54 UTC
